name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install Gradle
      uses: gradle/gradle-build-action@v2

    - name: Unzip source
      run: unzip SmsForwarder-home-settings-github-build.zip -d ./app-source

    - name: Build APK
      run: |
        cd ./app-source
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: smsforwarder-apk
        path: ./app-source/app/build/outputs/apk/debug/app-debug.apk
